application: pool
version: 1
runtime: python
api_version: 1

handlers:
- url: /s
  static_dir: public/stylesheets
    
- url: /i
  static_dir: public/images
  
- url: /j
  static_dir: public/javascripts
  
- url: .*
  script: pool.py
  
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin